apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: seeders.seeder.rinx.vald.vdaas.org
spec:
  group: seeder.rinx.vald.vdaas.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: seeders
    singular: seeder
    kind: Seeder
    shortNames:
      - sd
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            host:
              type: string
            port:
              type: integer
            edn:
              type: string
