---
apiVersion: v1
kind: Namespace
metadata:
  name: vald-seed-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vald-seed-operator
  namespace: vald-seed-operator
  labels:
    app: vald-seed-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vald-seed-operator
  template:
    metadata:
      labels:
        app: vald-seed-operator
    spec:
      serviceAccountName: vald-seed-operator
      containers:
        - name: vald-seed-operator
          imagePullPolicy: Always
          image: rinx/vald-seed-operator
          ports:
            - name: liveness
              containerPort: 3000
              protocol: TCP
            - name: readiness
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /liveness
              port: liveness
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /readiness
              port: readiness
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 300Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vald-seed-operator
  namespace: vald-seed-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vald-seed-operator
  namespace: vald-seed-operator
rules:
  - apiGroups:
      - seeder.rinx.vald.vdaas.org
    resources:
      - "*"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vald-seed-operator
  namespace: vald-seed-operator
subjects:
  - kind: ServiceAccount
    name: vald-seed-operator
    namespace: vald-seed-operator
roleRef:
  kind: ClusterRole
  name: vald-seed-operator
  apiGroup: rbac.authorization.k8s.io
